version: "3"
services: 
  babylon:
    image: babylon_explorer:1.0.0
    restart: always
    container_name: babylon_container
    ports:
      - "8001:8000"
      - "3002:3002"
      - "3001:3001"
    extra_hosts:
      - host.docker.internal:host-gateway